/**
 * Mogwai ERDesigner. Copyright (C) 2002 The Mogwai Project.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place - Suite 330, Boston, MA 02111-1307, USA.
 */
package de.mogwai.common.client.looks;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface LooksBundle {

	String BUNDLE_NAME = "de/mogwai/common/client/looks/LooksBundle";

	/** \u004f\u006b. */
	String OK = "OK";

	/** \u0041\u0062\u0062\u0072\u0065\u0063\u0068\u0065\u006e. */
	String CANCEL = "CANCEL";

	/** \u004a\u0061. */
	String YES = "YES";

	/** \u004e\u0065\u0069\u006e. */
	String NO = "NO";

}
