package de.mogwai.common.client.looks;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface LooksBundle {

  String BUNDLE_NAME = "de/mogwai/common/client/looks/LooksBundle";

  /** \u004f\u006b. */
  String OK = "OK";
  /** \u0041\u0062\u0062\u0072\u0065\u0063\u0068\u0065\u006e. */
  String CANCEL = "CANCEL";
  /** \u004a\u0061. */
  String YES = "YES";
  /** \u004e\u0065\u0069\u006e. */
  String NO = "NO";
}
