package de.mogwai.common.client.looks;

/**
 * Automatically generated by XMLResourceBundleTask. DO NOT ALTER !
 */
public interface LooksBundle {

  String BUNDLE_NAME = "de/mogwai/looks/LooksBundle";

  /** Ok */
  String OK = "OK";
  /** Abbrechen */
  String CANCEL = "CANCEL";
  /** Ja */
  String YES = "YES";
  /** Nein */
  String NO = "NO";
}
